[package]
name = "rtracer-rs"
version = "0.0.5"
authors = ["alekspickle <aleks.work2222@gmail.com>"]
edition = "2018"

[dependencies]
vek="0.9.9"
serde="1"
serde_json="1.0.41"
serde_derive="1"
image = "0.22.3"
num-traits = "0.2.8"
num-complex = "0.2.0"
termion="1.5.3"